unbind C-b
set-option -g prefix C-a

set-option -g set-clipboard on
 set -g mouse on

bind-key C-a send-prefix

bind o split-window -c "#{pane_current_path}"
bind p split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

bind-key - kill-window
bind-key x kill-pane

# Yank to system clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Use Vi mode
setw -g mode-keys vi


set -sg escape-time 5

#numbering windows and panes from 1
set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!" # quick reloajjd

set-option -g history-limit 5000
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# tmux themes
set -g @plugin 'niksingh710/minimal-tmux-status'
# These are the default values used inside the plugin to acheive the preview shown above.
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left false 

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

# Not recommended to change these values
set -g @minimal-tmux-status-right "#S"

# tmux ressurections
set -g @plugin 'tmux-plugins/tmux-resurrect'

# By default, tmux-resurrect only restores pane layout + commands, not full program state.
#
# Enable better restores:

set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-ssh 'session'

# Autosaves every 15 minutes
# Restores automatically on reboot

# set -g @plugin 'tmux-plugins/tmux-continuum'
#
# set -g @continuum-save-interval '15'
# set -g @continuum-restore 'on'

run '~/.config/tmux/plugins/tpm/tpm'
